[package]
name = "shex-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
shex-ast = { path = "../shex-ast" }
shex-lexer = { path = "../shex-lexer" }
thiserror = { workspace = true }
lalrpop-util = { version = "0.22", default-features = false }

[build-dependencies]
lalrpop = "0.22"

